name: foo

on:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        ghc:
          - 8.0.2
          - 8.2.2
          - 8.4.1
          - 8.4.2
          - 9.10.1
          - 9.12.1

        include:
          - os: macos-latest
            ghc: 9.12.2
         # - os: windows-latest
        #    ghc: system

    steps:
      - name: Export ImageOS
        run: echo "ImageOS=$ImageOS" >> $GITHUB_ENV
      - name: Install libncurses5 (only for GHC 8.0.2/8.2.2 on ubuntu22)
        if: env.ImageOS == 'ubuntu22' && (matrix.ghc == '8.0.2' || matrix.ghc == '8.2.2')
        run: sudo apt-get update && sudo apt-get install -y libncurses5
      - run: rm -rf /usr/local/.ghcup/*
      - run: |
          dst=$RUNNER_OS-$ImageOS-$RUNNER_ARCH-ghc-${{ matrix.ghc }}.tar.gz
          src=https://github.com/hspec/setup-haskell/releases/download/nightly/$dst
          echo "$src"
          gh release download nightly --repo hspec/setup-haskell -p "$dst" -O - | sudo tar -xzp -C /
          # curl -sSL "$src" | sudo tar -xzp -C /
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Add ghcup bin to PATH (macOS only)
        if: runner.os == 'macOS'
        run: echo "$HOME/.ghcup/bin" >> "$GITHUB_PATH"
      - run: ghc --version
      - run: cabal update
      - run: cabal install --package-env=. --lib hspec

