name: foo

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: rm -rf /usr/local/.ghcup/*
      - run: |
          src=https://github.com/hspec/setup-haskell/releases/download/nightly/dist-$RUNNER_OS-$RUNNER_ARCH.tar.gz
          curl -sSL "$src" | sudo tar -xzpfv
      - run: ghcup list
      - run: ghc --version
      - run: cabal update
      - run: cabal install --package-env=. --lib hspec

