name: foo

on:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        ghc:
          - 8.0.2
          - 8.2.2
          - 8.4.1
          - 8.4.2
          - 9.10.1
          - 9.12.1

        include:
          - os: macos-latest
            ghc: 9.12.2
         # - os: windows-latest
        #    ghc: system

    steps:
      - run: rm -rf /usr/local/.ghcup/*
      - run: |
          dst=$RUNNER_OS-$ImageOS-$RUNNER_ARCH-ghc-${{ matrix.ghc }}.tar.gz
          src=https://github.com/hspec/setup-haskell/releases/download/nightly/$dst
          echo "$src"
          # curl -sSL "$src" | sudo tar -xzp -C /
          status=$(curl -sSL -w "%{http_code}" -o /tmp/archive.tar.gz "$src")
          echo "HTTP status: $status"
          if [ "$status" -ne 200 ]; then
            echo "Download failed"
            exit 1
          fi
          sudo tar -xzp -C / -f /tmp/archive.tar.gz
      - name: Add ghcup bin to PATH (macOS only)
        if: runner.os == 'macOS'
        run: echo "$HOME/.ghcup/bin" >> "$GITHUB_PATH"
      - run: ghc --version
      - run: cabal update
      - run: cabal install --package-env=. --lib hspec

