name: foo

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - run: rm -rf /usr/local/.ghcup/*
      - run: |
          dst=$RUNNER_OS-$ImageOS-$RUNNER_ARCH-ghc-${{ matrix.ghc }}.tar.gz
          src=https://github.com/hspec/setup-haskell/releases/download/nightly/$dst
          curl -sSL "$src" | sudo tar -xzp -C /
      - run: ghcup list
      - run: ghc --version
      - run: cabal update
      - run: cabal install --package-env=. --lib hspec

