name: foo

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - run: rm -rf /usr/local/.ghcup/*
      - run: |
          src=https://github.com/hspec/setup-haskell/releases/download/nightly/ghc-9.10.1-$RUNNER_OS-$ImageOS-$RUNNER_ARCH.tar.gz
          echo "$src"
          echo "https://github.com/hspec/setup-haskell/releases/download/nightly/ghc-9.10.1-Linux-ubuntu22-X64.tar.gz"
          curl -sSL "$src" | sudo tar -xzp -C /
      - run: ghcup list
      - run: ghc --version
      - run: cabal update
      - run: cabal install --package-env=. --lib hspec

